# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-21 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophy', '0002_auto_20190318_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='profile-pic/'),
        ),
    ]
